spring.application.name=duitbetter_embedder
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=verystrongpassword
spring.ai.ollama.embedding.options.model=llama3.1
spring.ai.ollama.embedding.options.num-gpu=1
spring.ai.ollama.chat.options.num-gpu = 1
spring.ai.ollama.embedding.options.temperature=0.2
spring.ai.vectorstore.neo4j.initialize-schema=true
spring.ai.vectorstore.neo4j.label=WebPage
spring.ai.vectorstore.neo4j.embedding-dimension=4096
spring.ai.vectorstore.neo4j.id-property=url
spring.ai.vectorstore.neo4j.session-config.database=neo4j
spring.data.neo4j.database=neo4j
spring.ai.ollama.chat.enabled=true
spring.ai.ollama.chat.options.model=llama3.1
spring.ai.ollama.chat.options.temperature=0.2
logging.level.org.neo4j.ogm.drivers.bolt.request.BoltRequest=DEBUG